AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Metadata:
  AWS::ServerlessRepo::Application:
    Name: AlgernonShuckLine
    Description: the task queueing and routing layer for Algernon's Oyster
    Author: algernonsolutions
    SpdxLicenseId: AGPL-3.0
    LicenseUrl: LICENSE
    ReadmeUrl: README.md
    Labels: ['algernon']
    HomePageUrl: https://github.com/AlgernonSolutions/oyster.git
    SemanticVersion: 0.0.1
    SourceCodeUrl: https://github.com/AlgernonSolutions/oyster.git

Resources:
  Listener:
    Type: AWS::SNS::Topic
    Properties:
      DisplayName: !Sub "listener-${AWS::StackName}"
      KmsMasterKeyId: alias/aws/sns
      Subscription:
        - Endpoint: !GetAtt Queue.Arn
          Protocol: sqs
  Queue:
    Type: AWS::SQS::Queue
    Properties:
      VisibilityTimeout: 1500
      RedrivePolicy:
        deadLetterTargetArn:
          !GetAtt DeadLetter.Arn
        maxReceiveCount: 15
      KmsMasterKeyId: !Ref MasterKey
  QueuePolicy:
    Type: AWS::SQS::QueuePolicy
    Properties:
      PolicyDocument:
        Version: "2012-10-17"
        Id: "GentlemenSqsPolicy"
        Statement:
          - Effect: Allow
            Principal: "*"
            Action: "SQS:SendMessage"
            Resource: !GetAtt Queue.Arn
            Condition:
              ArnEquals:
                aws:SourceArn: !Ref Listener
      Queues:
        - !Ref Queue
  MasterKey:
    Type: AWS::KMS::Key
    Properties:
      KeyPolicy:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - "sns.amazonaws.com"
                - "lambda.amazonaws.com"
            Action:
              - "kms:GenerateDataKey*"
              - "kms:Decrypt"
            Resource: "*"
          - Effect: Allow
            Principal:
              AWS: !Join
                - ''
                - - 'arn:aws:iam::'
                  - !Ref 'AWS::AccountId'
                  - ':root'
            Action:
              - "kms:*"
            Resource: "*"
  DeadLetter:
    Type: AWS::SQS::Queue
    Properties:
      KmsMasterKeyId: alias/aws/sqs
      MessageRetentionPeriod: 1209600

Outputs:
  ListenerArn:
    Description: the ARN of the SNS notification topic
    Value: !Ref Listener
  QueueArn:
    Description: the ARN of the SQS queue used for buffering
    Value: !GetAtt Queue.Arn
  DeadLetterArn:
    Description: the ARN of SQS queue used to handle bad messages
    Value: !GetAtt DeadLetter.Arn
